### ISSUE TITLE
Agree upon a common JSON format with other structured logging frameworks

### ISSUE THREAD

**Issue by bitc** [hynek/structlog#168]
Hi! I've recently become more interested in structured logging, and have looked into a few structured logging libraries.

You get amazing power when you dump the logs from all of your different systems and sources into a centralized log store, and can then view and analyze them as one whole.

What I've noticed though is that the various structured logging frameworks all save JSON log entries in similar, but slightly different schemas.

For example, for storing timestamps, this library uses the JSON key "timestamp", while other libraries use "time" or "at". Another area where libraries differ is in how they store log levels.

These small differences cause friction when analyzing the central logstore, which contains structured logs that have been collected from multiple systems/microservices.

For example, one service might tag warnings with the string "WARN" while another with the string "warning". So if I want to view only warnings, I need to take this difference into account and write a tricky "OR" filter expression.  This may seem minor, but these small inconsistencies cause great pain.

I believe that these small differences between the various structured logging libraries exist not because of any strongly held opinions, but simply because mainstream structured and centralized logging is still relatively young, and so there is no standard or common consensus.

I think it would be very beneficial to everyone if we could all unite around a common format.

To get things started, I have created a GitHub repository to centralize discussions here: <https://github.com/bitc/structured-logging-schema>

It contains a comparison between several structured logging libraries, summarizing the differences between them all. This can hopefully be a start to help us arrive at common ground.

I encourage the authors of this library (and anyone else who has an opinion) to participate in the discussion!

Discussion takes place in the issues for this repo: <https://github.com/bitc/structured-logging-schema>

**Comment by hynek** [comment]
Yeah when I started structlog back in 2014, this was all new and shiny and there weren’t any real role models.

A bunch of comments:

- Overall, many of the points raised are kinda invalid for structlog because it's very pluggable and configurable. It’s just dictionaries (hash maps) until the very end when they are run thru a pipeline of callables that take a dict and return a dict. So essentially *anything* and *any* format is possible.
- The message JSON key is actually `event` and the payload is merged into root. But you could write yourself a processor that transforms the event dictionary in the last step. `¯\_(ツ)_/¯`
- The timestamp field name is [configurable](http://www.structlog.org/en/latest/api.html#structlog.processors.TimeStamper) if you use the shipped timestamper. Or you write your own timestamper – it’s like five lines of code.
- Log levels are currently inherited from standard library logging – structlog itself has no concept of it. So you basically can implement any level you wish. If you don't use stdlib logging, you actually lose them.
- System context data can be trivially added using a processor – same for HTTP request context data.

While I do appreciate your efforts to collect & standardize (I wish that existed in 2014), I cannot see a way for myself to change the defaults because that would cause breakage. :(
