### ISSUE TITLE
How to support structlog within a library?

### ISSUE THREAD

**Issue by adamcharnock** [hynek/structlog#179]
Firstly, thank you for writing structlog, I'm just reading into it now and it seems like a really useful tool.

**I'm developing a Python library and I would like to support structlog, while not mandating it's use.**

My thinking so far is that:

* The developer (i.e. user of my library) should responsible for the logging setup
* I will log key/value pairs with each log message to give extra context
* If the developer uses structlog, they would get the benefit of seeing these key/value pairs
* If the user does not use structlog, they regular log messages

I read through the [stdlib section](http://www.structlog.org/en/stable/standard-library.html) of the docs, but I couldn't quite divine the best way to proceed. Any advice you can offer would be a great help. Thank you!

**Comment by hynek** [comment]
Sorry for my late response, I was traveling.

Yeah there are basically two problems to be solved:

1. **How to configure?** I think the user should configure structlog themselves and should be required to tell your lib *explicitly* that it wants to use structlog.
2. **How to log?** Since structlog with its k/v support is a superset of logging and you want k/v logging this is not trivial. I think the best way would be to write a very thin shim that allows for `log.info("event", x=y, a=b)` and if structlog is not used, it’s will either format the k/v or transform it into logging-specific context information by passing it into `logging.info("event", extra={"x": y, "a": b})`?

Point 2 is mostly just a suggestion/request for comments, since nobody has done that publicly so far…

**Comment by abdulhaq-e** [comment]
For anyone passing by here, `litestar` has this implemented where it allows users to choose their logging library (standard, structlog or Picologging) while using the same interface.

Check this: https://github.com/litestar-org/litestar/blob/main/litestar/types/protocols.py
