### ISSUE TITLE
JSONRenderer and not serializable dict keys

### ISSUE THREAD

**Issue by askurihin** [hynek/structlog#265]
This code

```python

import uuid
import structlog             

structlog.configure(processors=[structlog.processors.JSONRenderer()]) 
structlog.get_logger().info({uuid.uuid4(): 1})
```

fails with `TypeError`

```python
TypeError: keys must be str, int, float, bool or None, not UUID
```

In my setup, I can fix this issue by using a custom json encoder, passed to json.dums using `cls` argument.
What do you suggest, fix the issue in structlog code or mention this case in the docs?

**Comment by hynek** [comment]
This seems a _very_ fringe use-case. Ultimately, if you want to pass non-standard datatypes into your log entries, you have to customize dumps anyway. If you want to have non-standard keys, that's even more true. I would recommend to do it via `default` argument if possible though.

**Comment by askurihin** [comment]
I didn't manage to make it work via `default` argument, as far as I understood, `default` is applied to values, not keys.

I think that is quite a fringe use-case, sure, but it can be useful for someony If it is mentioned in the docs.
Will you accept a PR with such change?

**Comment by hynek** [comment]
Yes, because it’s rather unexpected that someone uses anything else than strings as keys.  😅

This use-case by itself is nothing I would want to add to the docs, since they are quite extensive already.

What I could imagine is an isolated chapter specifically on JSON logs that explains some beste practices and logging of custom types.
