### ISSUE TITLE
stdlib getChild returns logging object and not wrapped?

### ISSUE THREAD

**Issue by seanv507** [hynek/structlog#298]
```{python}
import logging
import structlog
structlog.configure(
    processors=[
        structlog.stdlib.ProcessorFormatter.wrap_for_formatter,
    ],
    logger_factory=structlog.stdlib.LoggerFactory(),
    wrapper_class=structlog.stdlib.BoundLogger,
)

formatter = structlog.stdlib.ProcessorFormatter(
    processor=structlog.dev.ConsoleRenderer(),
)

handler = logging.StreamHandler()
handler.setFormatter(formatter)
root_logger = logging.getLogger()
root_logger.addHandler(handler)
root_logger.setLevel(logging.INFO)
par=structlog.getLogger("Parent")
par.info("hello",x="hello")
child1=par.getChild("Child")
child1.info("hello", child="child")
```

has exception
`TypeError: _log() got an unexpected keyword argument 'child'`

I assume this is because it is returning the unwrapped child logger?

**Comment by hynek** [comment]
You assume correctly: the call is forwarded 1:1 to stdlib IIRC. You should be able to use wrap_logger on it? 🤔

**Comment by seanv507** [comment]
Will try that ( I am just a beginner in logging and structlog :) ) but would you classify this as a bug? or what's the rationale

**Comment by hynek** [comment]
It's a bit unclear, because we've claimed that we pass everything through, except for the actual logging. I believe, that it was added en block with other methods and there literally was no rationale. If I knew about this when adding, I might have done it differently but at this point it would break backward compat if we changed its behavior.
