### ISSUE TITLE
Suggestions for performance increase

### ISSUE THREAD

**Issue by Goldziher** [hynek/structlog#444]
Hiya,

I'd like to make two suggestions for performance increase:

1. use `orjson` instead of the builtin json library: https://github.com/ijl/orjson, it will vastily increase the speed of encoding json and its "default" option allows for customizing serialization.
2. use `picologging` instead of the native logging module as a basis: https://github.com/microsoft/picologging, it will make the outputting of logs significantly faster as well. 

I understand that point 2 might be problematic, I would therefore suggest making the switch automatically. See how this is handled for example in Starlite:  https://github.com/starlite-api/starlite/blob/main/starlite/config/logging.py#L71

**Comment by hynek** [comment]
orjson is already mentioned in https://www.structlog.org/en/stable/performance.html – picologging is a bit too green behind its ears to be full-on recommendation.

**Comment by Goldziher** [comment]
cheers. I updated our usage to be based on the example you gave.

Another question - Starlite is an ASGI API Framework, as such we are using QueueListener handlers in regular logging, to ensure its non-blocking. Is there something similar in orjson?

**Comment by hynek** [comment]
orjson is for serializing log entries to strings, not for output.

As you've noticed there's AsyncBoundLogger for stdlib-based setups, but I didn't get around to implement one for non-stdlib. It shouldn't be too hard and if you'd use stdlib, you can keep using QueueListener in the first place.

This is pick and choose depending on your needs & context. And you should double-check whether the impact is really that big, because spinning up worker threads is not free and if you're just dumbing bytes into stdout after serializing it with orjson, you may be fine as is.

**Comment by Goldziher** [comment]
Thanks. It's not for me. We are creating a generic logging wrapper with defaults. I want to config it for optimal usage out of the box and save users the trouble.

**Comment by Goldziher** [comment]
Here, https://github.com/starlite-api/starlite/blob/main/starlite/config/logging.py#L205

Any suggestions would be welcome.

**Comment by Goldziher** [comment]
can you show me how to combine

**Comment by hynek** [comment]
Looks decent – thanks for integrating it! You may want to watch #354 getting closed for non-stdlib async support
