### ISSUE TITLE
Cannot bind event key with `make_filtering_bound_logger`

### ISSUE THREAD

**Issue by vedantroy** [hynek/structlog#456]
This post: https://stackoverflow.com/questions/74083659/how-to-set-log-level-with-structlog-when-not-using-event-parameter serves as a good reference for the problem.

TL;DR:

```
                l = logger.bind(event="get_tar", key=value)
                l.info(status="download_start")
                buf = f.read()
                l.info(status="download_finish")
```

doesn't work wtih: `make_filtering_bound_logger`

**Comment by hynek** [comment]
my biggest surprise here is that you apparently can bind `event` on the generic one.

i've added a [recipe on renaming the `event` key](https://www.structlog.org/en/latest/recipes.html#renaming-the-event-key) which may be relevant to your interests.

otherwise as i wrote on SO, `event` is hardcoded…
