### ISSUE TITLE
how to migrate from `wrap_dict` to contextvars?

### ISSUE THREAD

**Issue by asottile-sentry** [hynek/structlog#487]
I unfortunately have very little context to the code I'm maintaining here so I'll try and simplify it down as much as possible:

https://github.com/getsentry/sentry/blob/06b8f6532b0988ca4485e8b42cfd2942e37a302e/src/sentry/runner/initializer.py#L243-L272

I understand the difference between thread locals and `contextvars`, but I'm not sure how to migrate from one to the other given `structlog` -- https://www.structlog.org/en/stable/thread-local.html#structlog.threadlocal.wrap_dict

I guess what I'm looking for is a `contextvars` equivalent of this? and/or documentation recommending how to move to it?

**Comment by hynek** [comment]
Oof, does Sentry actually assume the behavior of `wrap_dict`? Because it's a not a great behavior. 😅

Correct way forward would be to switch to the explicit `bind_contextvars` calls, but if that's too much effort, the smoothest way I guess would be to reimplement:

- [`wrap_dict`](https://github.com/hynek/structlog/blob/bcfc7f9e60640c150bffbdaeed6328e582f93d1e/src/structlog/threadlocal.py#L81-L98)
- [`_ThreadLocalDictWrapper`](https://github.com/hynek/structlog/blob/bcfc7f9e60640c150bffbdaeed6328e582f93d1e/src/structlog/threadlocal.py#L156-L221)

Both are trivial and only a handful of lines of code so I guess that's more realistic for you? I can help you writing it, but I'm not excited to encourage that pattern (transparent global state) by adding it to structlog proper. :-/

**Comment by asottile-sentry** [comment]
> Oof, does Sentry actually assume the behavior of `wrap_dict`? Because it's a not a great behavior. sweat_smile

that's a gooooood question, that I don't think anyone knows the answer to :upside_down_face: (this was apparently added in 2016) -- is there a good way for me to know whether it's being depended on or not?

if I don't see any calls to `.new(` or `.bind(` or `.unbind(` am I safe to assume this is lost to the sands of time? (I'm trying the testsuites without it now -- will report back)

**Comment by asottile-sentry** [comment]
I guess we weren't using it -- someone removed it and they seem happy with the results :shrug:

**Comment by hynek** [comment]
😮‍💨
