### ISSUE TITLE
Allow positional arguments without configuring stdlib integration

### ISSUE THREAD

**Issue by jamespic** [hynek/structlog#76]
I'm aware of #70, and totally understand the arguments against it. This is not a request for that.

In our project, we've adopted structlog with the stdlib configuration, as a drop-in replacement, to allow us to gradually move to a more structured approach. However, one pain point is that during unit testing, if we haven't configured `structlog`, any logging calls that have positional arguments fail because `BoundLoggerBase._proxy_to_logger` does not accept positional arguments.

An implementation that didn't throw an exception in this case would be useful (for example, the approach used in `stdlib.BoundLogger._proxy_to_logger` of putting them into a key called `'positional_args'` would work great), since we could write unit tests without having to think about logging config.

Happy to raise a PR for this, but wanted to check that the approach would be acceptable before starting work.

**Comment by hynek** [comment]
What is practically stopping you from configuring structlog in your tests?  This reminds me a bit of #71 – maybe there’s some inspiration (from Mozilla Services no less) for you?

***

Generally speaking I try to keep my APIs as tight as possible such that subtle mistakes/bugs explode early and loudly.  Therefore I’m rather unsympathetic to such changes. :|

**Comment by jamespic** [comment]
Nothing prevents us adding logging setup to tests per se, but logging setup in a test is noise that distracts from the purpose of the test (if that purpose isn't logging related).

I'm also concerned about what happens when a second developer tries to test the code in a different setting, and it blows up with an unintuitive log exception - I've spent enough of my career being that second developer to be wary of logging frameworks with non-usable defaults.

I can understand the desire to keep the API tight, but it was a surprise to me that configuring structlog changed its API.

**Comment by hynek** [comment]
Hm, I don’t know if you use pytest because I just have an autouse fixture for that:

```python
@pytest.fixture(autouse=True)
def configure_structlog():
    """
    Configures cleanly structlog for each test method.
    """
    structlog.reset_defaults()
    structlog.configure(
        processors=[
            structlog.processors.StackInfoRenderer(),
            structlog.processors.format_exc_info,
            structlog.processors.KeyValueRenderer(),
        ],
        wrapper_class=BoundLogger,
        context_class=dict,
        logger_factory=LoggerFactory(),
        cache_logger_on_first_use=False,
    )
```

(just leaving it here for posterity)

***

I feel your pain about surprises and I realize, that structlog’s versatility has it’s price (= can act in surprising ways w/o configuration if you integrate it with something).  But being able to change the API of the loggers and wrappers is an important feature; otherwise it would be impossible to integrate with logging system. :)

I guess at this point the question really just is: what are the downsides of moving the `event_kw['positional_args']` feature from stdlib’s BoundLogger to the generic one.  Will that lead to other surprising behaviors that pass by silently?
